using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace WrongWarp
{
    [CreateAssetMenu(fileName = "New Background Generator", menuName = "Assets/Inventory/BackgroundGenerator")]
    public class BackgroundGenerator : ScriptableObject
    {
        [Header("Background Visuals")]
        [Tooltip("Background generator to use. If this doesn't exist, will use defaultBackground.")]
        [SerializeField] private GameObject backgroundGenerator;
        /// <summary> Returns the sprite generated by this inventory preset. </summary>
        public Sprite GetBackground(int width, int height, ServerSimpleItem[] items)
        {
            if (backgroundGenerator == null)
            {
                if (backgroundSprite == null)
                {
                    Debug.Log("ERROR: Inventory preset does not have a background image to use.");
                    return null;
                }
                return backgroundSprite;
            }
            return backgroundGenerator.GetComponent<IImageGenerator>().GenerateSprite(width, height, items);
        }

        [Tooltip("Does this background change with the inventory?")]
        [SerializeField] public bool isDynamicBackground = false;

        [Space]

        [Tooltip("The sprite to use (by default, should only be used if imageGenerator doesn't exist")]
        [SerializeField] private Sprite backgroundSprite;


        [Tooltip("What color should this background have?")]
        [SerializeField] private Color32 baseColor = new Color32(1, 1, 1, 1);
    }
}
